version: "3.9"
services:
  postgres:
    image: postgres:14.9-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data-tutodo:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data-tutodo: